Improve Document Commits workflow (#185)
* feat: Compare base branch with test branch at start

* feat: Improve API call when retrieving feature PR

diff --git a/.github/workflows/DocumentMergedCommits.yaml b/.github/workflows/DocumentMergedCommits.yaml
--- a/.github/workflows/DocumentMergedCommits.yaml
+++ b/.github/workflows/DocumentMergedCommits.yaml
@@ -11,6 +11,7 @@ env:
   COMMIT_COMMENT_TAG: <!-- UpdateTestBranch/COMMIT -->
   BOT_LABEL: Automated
   FEATURE_TEST_PREFIX: test/
+  TEST_BRANCH: test/main
   SKIP_ALL: false
   ADDED_COMMITS: ''
   PICKED_COMMITS: ''
@@ -24,32 +25,38 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set environment variables
-        if: ${{ env.SKIP_ALL == 'false' }}
         run: |
           echo "NOTICE_COMMENT_TAG=${{ vars.UPDATETESTBRANCH_NOTICE_COMMENT_TAG || env.NOTICE_COMMENT_TAG }}" >> $GITHUB_ENV
           echo "COMMIT_COMMENT_TAG=${{ vars.UPDATETESTBRANCH_COMMIT_COMMENT_TAG || env.COMMIT_COMMENT_TAG }}" >> $GITHUB_ENV
           echo "BOT_LABEL=${{ vars.UPDATETESTBRANCH_BOT_LABEL || env.BOT_LABEL }}" >> $GITHUB_ENV
           echo "FEATURE_TEST_PREFIX=${{ vars.UPDATETESTBRANCH_FEATURE_TEST_PREFIX || env.FEATURE_TEST_PREFIX }}" >> $GITHUB_ENV
+          echo "TEST_BRANCH=${{ vars.UPDATETESTBRANCH_TEST_BRANCH || env.TEST_BRANCH }}" >> $GITHUB_ENV
 
       - name: Check if head branch is a feature test branch
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
           head_branch="${{ github.head_ref }}"
           feature_test_prefix="${{ env.FEATURE_TEST_PREFIX }}"
+          base_branch="${{ github.base_ref }}"
+          if [ "$base_branch" != ${{ env.TEST_BRANCH }} ]; then
+            echo "SKIP_ALL=true" >> $GITHUB_ENV
+            echo "::notice::PR is not targeting test branch ${{ env.TEST_BRANCH }}. Skipping."
+            exit 0
+          fi
           if [[ "$head_branch" != $feature_test_prefix* ]]; then
             echo "$head_branch is not a feature test branch. Skipping..."
             echo "SKIP_ALL=true" >> $GITHUB_ENV
+            exit 0
+          fi
+
+          feature_branch=${head_branch#$feature_test_prefix}
+          if [ -z "$feature_branch" ]; then
+            echo "::error::Unable to determine feature branch name from $head_branch with prefix $feature_test_prefix."
+            echo "SKIP_ALL=true" >> $GITHUB_ENV
+            exit 1
           else
-            head_branch=$head_branch
-            feature_branch=${head_branch#$feature_test_prefix}
-            if [ -z "$feature_branch" ]; then
-              echo "::error::Unable to determine feature branch name from $head_branch with prefix $feature_test_prefix."
-              echo "SKIP_ALL=true" >> $GITHUB_ENV
-              exit 1
-            else
-              echo "Feature branch should be called $feature_branch."
-              echo "FEATURE_BRANCH=$feature_branch" >> $GITHUB_ENV
-            fi
+            echo "Feature branch should be called $feature_branch."
+            echo "FEATURE_BRANCH=$feature_branch" >> $GITHUB_ENV
           fi
 
       - name: Set up Git
@@ -70,24 +77,18 @@ jobs:
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
           feature_branch="${{ env.FEATURE_BRANCH }}"
-          prs_json=$(gh pr list --json headRefName,number)
-          printf "::debug::PR info: %q\n" "$pr_info"
-
-          feature_pr_json=$(echo "$prs_json" | jq --arg feature_branch "$feature_branch" '.[] | select(.headRefName == $feature_branch)')
-          if [ -z "$feature_pr_json" ]; then
-          echo "SKIP_ALL=true" >> $GITHUB_ENV
+          pr_json=$(gh pr view $feature_branch --json title,number 2>/dev/null)
+          if [ $? != 0 ]; then
+            echo "SKIP_ALL=true" >> $GITHUB_ENV
             echo "::error::Unable to find PR with head ref $feature_branch."
             exit 1
           fi
-          feature_pr_number=$(echo "$feature_pr_json" | jq '.number')
-          if [ -n "$feature_pr_number" ]; then
-            echo "FEATURE_PR_NUMBER=$feature_pr_number" >> $GITHUB_ENV
-          else
-            echo "$feature_pr_json"
-            echo "::error::Unable to extract PR number from JSON response."
-            echo "SKIP_ALL=true" >> $GITHUB_ENV
-            exit 1
-          fi
+
+          pr_number=$(echo "$pr_json" | jq '.number')
+          pr_title=$(echo "$pr_json" | jq -r '.title' | tr -dc 'A-Za-z0-9 ')
+
+          echo "FEATURE_PR_NUMBER=$pr_number" >> $GITHUB_ENV
+          echo "Feature PR: #$pr_number - $pr_title"
 
       - name: Get newly added commits
         id: list-commits
