Fix error in feature branch assignment

diff --git a/.github/workflows/DocumentMergedCommits.yaml b/.github/workflows/DocumentMergedCommits.yaml
--- a/.github/workflows/DocumentMergedCommits.yaml
+++ b/.github/workflows/DocumentMergedCommits.yaml
@@ -37,9 +37,16 @@ jobs:
             echo "${{ github.head_ref }} is not a feature test branch. Skipping..."
             echo "SKIP_ALL=true" >> $GITHUB_ENV
           else
-            feature_branch=${${{github.head_ref}}#${{ env.FEATURE_TEST_PREFIX }}}
-            echo "Feature branch should be called $feature_branch."
-            echo "FEATURE_BRANCH=$feature_branch" >> $GITHUB_ENV
+            head_branch=${{github.head_ref}}
+            feature_branch=${head_branch#${{ env.FEATURE_TEST_PREFIX }}}
+            if [ -z "$feature_branch" ]; then
+              echo "::error::Unable to determine feature branch name from $head_branch with prefix ${{env.FEATURE_TEST_PREFIX}}."
+              echo "SKIP_ALL=true" >> $GITHUB_ENV
+              exit 1
+            else
+              echo "Feature branch should be called $feature_branch."
+              echo "FEATURE_BRANCH=$feature_branch" >> $GITHUB_ENV
+            fi
           fi
 
       - name: Set up Git
@@ -60,17 +67,20 @@ jobs:
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
           prs_json=$(gh pr list --json headRefName,number)
+          printf "::debug::PR info: %q\n" "$pr_info"
+
           feature_pr_json=$(echo $prs_json | jq --arg feature_branch "${{ env.FEATURE_BRANCH }}" '.[] | select(.headRefName == $feature_branch)')
           if [ -z "$feature_pr_json" ]; then
-            echo "Unable to find PR with head ref ${{ env.FEATURE_BRANCH }}."
-            echo "SKIP_ALL=true" >> $GITHUB_ENV
+          echo "SKIP_ALL=true" >> $GITHUB_ENV
+            echo "::error::Unable to find PR with head ref ${{ env.FEATURE_BRANCH }}."
             exit 1
           fi
           feature_pr_number=$(echo $feature_pr_json | jq '.number')
           if [ -n "$feature_pr_number" ]; then
             echo "FEATURE_PR_NUMBER=$feature_pr_number" >> $GITHUB_ENV
           else
-            echo "Unable to find PR with head ref ${{ env.FEATURE_BRANCH }}."
+            echo $feature_pr_json
+            echo "::error::Unable to extract PR number from JSON response."
             echo "SKIP_ALL=true" >> $GITHUB_ENV
             exit 1
           fi
