Copy workflow file from #1 & move outputs to environment scope

diff --git a/.github/workflows/UpdateTestBranch.yaml b/.github/workflows/UpdateTestBranch.yaml
--- a/.github/workflows/UpdateTestBranch.yaml
+++ b/.github/workflows/UpdateTestBranch.yaml
@@ -1,4 +1,3 @@
-# This version of the workflow is for the test branch only.
 name: Update Test Branch
 
 on:
@@ -16,9 +15,15 @@ env:
   TRIGGER_LABEL: Ready for Test
   BOT_COMMENT_TAG: <!-- Test -->
   BOT_LABEL: Automated
-  SKIP_TAG: skip
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   DISABLE_COMMENTS: false
+  SKIP: false
+  NEWEST_COMMIT_HASH: ''
+  CHERRY_PICK_BRANCH: ''
+  MERGE_COMMIT_SHA: ''
+  MERGE_COMMIT_MSG: ''
+  TEST_PR_URL: ''
+  COMMENT_URL: ''
 
 jobs:
   update_test_branch:
@@ -27,29 +32,21 @@ jobs:
     steps:
       - name: Check PR status
         id: check_pr
-        continue-on-error: true
-        uses: actions/github-script@v7
-        with:
-          script: |
-            if (context.payload.pull_request.head.ref === process.env.TEST_BRANCH) {
-              core.setFailed(`You cannot update the ${process.env.TEST_BRANCH} branch with itself. Please use a different branch.`);
-            }
-            if (context.payload.pull_request.head.ref.startsWith('${{ env.SKIP_TAG }}/')) {
-              core.setFailed(`The head branch of this pull request begins with "${{ env.SKIP_TAG }}/". Changes from this branch will not be cherry-picked into the ${process.env.TEST_BRANCH} branch.`);
-            }
+        run: |
+          if [ "${{ github.head_ref }}" == "${{ env.TEST_BRANCH }}" ]; then
+            echo "::error::You cannot update the test branch `${{ env.TEST_BRANCH }}` with itself. Please use a different branch."
+            exit 1
+          fi
 
       - name: Checkout repository
-        if: ${{ steps.check_pr.outcome == 'success' }}
         uses: actions/checkout@v4.1.1
 
       - name: Set up Git
-        if: ${{ steps.check_pr.outcome == 'success' }}
         run: |
           git config --global user.name github-actions[bot]
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
       - name: Ensure trigger label exists
-        if: ${{ steps.check_pr.outcome == 'success' }}
         run: |
           if [ -z "$(gh label list --search "${{ env.TRIGGER_LABEL }}" --limit 1)" ]; then
             gh label create ${{ env.TRIGGER_LABEL }} --color fa8825 --description "Ready to be added to the test branch."
@@ -58,19 +55,16 @@ jobs:
 
       - name: Check if label matches trigger label
         id: check_label
-        continue-on-error: true
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const triggerLabel = "${{ env.TRIGGER_LABEL }}";
-            const eventLabel = context.payload.label.name;
-            if (eventLabel !== triggerLabel) {
-              core.setFailed(`The label "${eventLabel}" is not the required label "${triggerLabel}".`);
-            }
+        run: |
+          triggerLabel="${{ env.TRIGGER_LABEL }}"
+          eventLabel="${{ github.event.label.name }}"
+          if [ "$eventLabel" != "$triggerLabel" ]; then
+            echo "SKIP=true" >> "$GITHUB_ENV"
+          fi
 
       - name: Check if ${{ env.TEST_BRANCH }} exists
         id: check_test_branch
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         uses: actions/github-script@v7
         with:
           script: |
@@ -83,18 +77,18 @@ jobs:
 
       - name: Get newest commit hash
         id: get_commit_hash
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           newest_commit_hash=$(git rev-parse --short HEAD)
-          echo "NEWEST_COMMIT_HASH=$newest_commit_hash" >> "$GITHUB_OUTPUT"
+          echo "NEWEST_COMMIT_HASH=$newest_commit_hash" >> "$GITHUB_ENV"
           echo "Newest commit hash (short): $newest_commit_hash"
 
       - name: Create temporary cherry-pick branch of target branch
         id: create_temp_branch
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
-          cherry_pick_branch="${{ env.CPICK_BRANCH_TEMPLATE }}/${{ steps.get_commit_hash.outputs.NEWEST_COMMIT_HASH }}"
-          echo "CHERRY_PICK_BRANCH=$cherry_pick_branch" >> "$GITHUB_OUTPUT"
+          cherry_pick_branch="${{ env.CPICK_BRANCH_TEMPLATE }}/${{ env.NEWEST_COMMIT_HASH }}"
+          echo "CHERRY_PICK_BRANCH=$cherry_pick_branch" >> "$GITHUB_ENV"
           git fetch origin ${{ github.base_ref }}
           git checkout ${{ github.base_ref }}
           git checkout -b $cherry_pick_branch
@@ -102,30 +96,30 @@ jobs:
       - name: Squash merge ${{ github.head_ref }} into temporary cherry-pick branch
         id: merge_commit
         continue-on-error: true
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           git fetch origin ${{ github.head_ref }}
-          merge_commit_msg='Cherry-pick changes from `${{ github.head_ref }}` up to `${{ steps.get_commit_hash.outputs.NEWEST_COMMIT_HASH }}`'
+          merge_commit_msg='Cherry-pick changes from `${{ github.head_ref }}` up to `${{ env.NEWEST_COMMIT_HASH }}`'
 
           git merge --squash -n "origin/${{ github.head_ref }}"
           if [ -n "$(git status --porcelain | grep '^U')" ]; then
             exit 1
           fi
           git commit -m "$merge_commit_msg"
-          git push origin "${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}"
+          git push origin "${{ env.CHERRY_PICK_BRANCH }}"
 
-          echo "MERGE_COMMIT_MSG=$merge_commit_msg" >> "$GITHUB_OUTPUT"
-          echo "MERGE_COMMIT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
+          echo "MERGE_COMMIT_MSG=$merge_commit_msg" >> "$GITHUB_ENV"
+          echo "MERGE_COMMIT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
 
       - name: Report Error
-        if: ${{ steps.check_label.outcome == 'success' && steps.merge_commit.outputs.MERGE_COMMIT_SHA == '' }}
+        if: ${{ env.SKIP == 'false' && env.MERGE_COMMIT_SHA == '' }}
         uses: actions/github-script@v7
         with:
           script:
             core.setFailed('Unable to create squash merge commit. Please merge the latest changes to `${{ github.base_ref }}` into the head branch `${{ github.head_ref }}` and try again.')
 
       - name: Create/Checkout ${{ env.FEATURE_TEST_BRANCH }}
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           git fetch origin ${{ env.TEST_BRANCH }}
           if [ -z "$(git ls-remote --heads origin ${{ env.FEATURE_TEST_BRANCH }})" ]; then
@@ -140,12 +134,12 @@ jobs:
       - name: Cherry-pick squash merge commit
         continue-on-error: true
         id: cherry_pick
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
-          git cherry-pick --no-commit ${{ steps.merge_commit.outputs.MERGE_COMMIT_SHA }} || true
+          git cherry-pick --no-commit ${{ env.MERGE_COMMIT_SHA }} || true
           git status --porcelain | grep '^U'
           if [ -n "$(git status --porcelain | grep '^U')" ]; then
-            echo '::error::Cherry-pick failed. Please cherry-pick the commit "${{ steps.merge_commit.outputs.MERGE_COMMIT_MSG }}" (`${{ steps.merge_commit.outputs.MERGE_COMMIT_SHA }}`) into `${{ env.FEATURE_TEST_BRANCH }}` manually.'
+            echo '::error::Cherry-pick failed. Please cherry-pick the commit "${{ env.MERGE_COMMIT_MSG }}" (`${{ env.MERGE_COMMIT_SHA }}`) into `${{ env.FEATURE_TEST_BRANCH }}` manually.'
             exit 1
           else
             echo "Cherry-pick successful."
@@ -155,7 +149,7 @@ jobs:
         if: ${{ steps.cherry_pick.outcome == 'success' }}
         run: |
           if [ -n "$(git status --porcelain)" ]; then
-            git commit -m '${{ steps.merge_commit.outputs.MERGE_COMMIT_MSG }}'
+            git commit -m '${{ env.MERGE_COMMIT_MSG }}'
           fi
           if [ -z "$(git log origin/${{ env.FEATURE_TEST_BRANCH }}..${{ env.FEATURE_TEST_BRANCH }})" ]; then
             git push origin ${{ env.FEATURE_TEST_BRANCH }}
@@ -164,20 +158,20 @@ jobs:
       - name: "On success: Cleanup cherry-pick branch"
         if: ${{ steps.cherry_pick.outcome == 'success' }}
         run: |
-          git branch -D ${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}
-          git push origin --delete ${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}
+          git branch -D ${{ env.CHERRY_PICK_BRANCH }}
+          git push origin --delete ${{ env.CHERRY_PICK_BRANCH }}
           git branch | grep '${{ env.CPICK_BRANCH_TEMPLATE }}' | xargs -I {} git push origin --delete {}
 
       - name: "On failure: Abort cherry-pick & add empty commit"
         if: ${{ steps.cherry_pick.outcome == 'failure' }}
         run: |
           git reset --hard
-          git commit --allow-empty -m 'Cherry-pick of `${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}` failed.
+          git commit --allow-empty -m 'Cherry-pick of `${{ env.CHERRY_PICK_BRANCH }}` failed.
           Manual resolution required.'
           git push origin ${{ env.FEATURE_TEST_BRANCH }}
 
       - name: Ensure bot label exists
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           if [ -z "$(gh label list --search "${{ env.BOT_LABEL }}" --limit 1)" ]; then
             gh label create ${{ env.BOT_LABEL }} --color AAAAAA --description "Automated pull requests"
@@ -186,7 +180,7 @@ jobs:
 
       - name: Create/Update pull request
         id: create_pr
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           if [ "$(gh pr list --base ${{ env.TEST_BRANCH }} --head ${{ env.FEATURE_TEST_BRANCH }} --state open | wc -l)" == 0 ]; then
             TEST_PR_URL=$(gh pr create \
@@ -203,10 +197,10 @@ jobs:
               --add-assignee ${{ github.actor }})
             echo "::notice::$TEST_PR_URL updated."
           fi
-          echo "TEST_PR_URL=$TEST_PR_URL" >> "$GITHUB_OUTPUT"
+          echo "TEST_PR_URL=$TEST_PR_URL" >> "$GITHUB_ENV"
 
       - name: Set pull request status
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           if [ "${{ steps.cherry_pick.outcome }}" == "success" ]; then
             gh pr ready ${{ env.FEATURE_TEST_BRANCH }}
@@ -215,11 +209,11 @@ jobs:
           fi
 
       - name: Clean up comments
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         uses: actions/github-script@v7
         with:
           script: |
-            const urlSubstrings = "${{ steps.create_pr.outputs.TEST_PR_URL }}".split('/')
+            const urlSubstrings = "${{ env.TEST_PR_URL }}".split('/')
             const newPrNumber = urlSubstrings[urlSubstrings.length - 1]
             const oldPrComments = github.rest.issues.listComments({
               issue_number: context.issue.number,
@@ -247,7 +241,7 @@ jobs:
 
       - name: Comment on the new pull request
         id: comment_new_pr
-        if: ${{ steps.check_label.outcome == 'success' && env.DISABLE_COMMENTS == 'false' }}
+        if: ${{ env.SKIP == 'false' && env.DISABLE_COMMENTS == 'false' }}
         run: |
           body='**Automatic ${{ env.TEST_BRANCH }} update failed.**
 
@@ -258,36 +252,36 @@ jobs:
           git fetch origin ${{ env.FEATURE_TEST_BRANCH }}
           git checkout ${{ env.FEATURE_TEST_BRANCH }}
           git pull origin ${{ env.FEATURE_TEST_BRANCH }}
-          git cherry-pick ${{ steps.merge_commit.outputs.MERGE_COMMIT_SHA }} -e
+          git cherry-pick ${{ env.MERGE_COMMIT_SHA }} -e
           ```
           2) Resolve the merge conflicts and push the changes.
-          3) Delete the branch `${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}` with the following command:
+          3) Delete the branch `${{ env.CHERRY_PICK_BRANCH }}` with the following command:
           ```
-          git push origin --delete ${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}
+          git push origin --delete ${{ env.CHERRY_PICK_BRANCH }}
           ```
           4) Mark the pull request as ready for review to trigger the status checks.'
 
-          COMMENT_URL=$(gh pr comment ${{ steps.create_pr.outputs.TEST_PR_URL }} --body "${{ env.BOT_COMMENT_TAG }}
+          COMMENT_URL=$(gh pr comment ${{ env.TEST_PR_URL }} --body "${{ env.BOT_COMMENT_TAG }}
           $body")
           echo $COMMENT_URL
-          echo "COMMENT_URL=$COMMENT_URL" >> "$GITHUB_OUTPUT"
+          echo "COMMENT_URL=$COMMENT_URL" >> "$GITHUB_ENV"
 
       - name: Comment on the original pull request
-        if: ${{ steps.check_label.outcome == 'success' && env.DISABLE_COMMENTS == 'false' }}
+        if: ${{ env.SKIP == 'false' && env.DISABLE_COMMENTS == 'false' }}
         run: |
           if [ "${{ steps.cherry_pick.outcome }}" == "success" ]; then
             body='The cherry-picked changes from `${{ github.head_ref }}` are ready to be added to the `${{ env.TEST_BRANCH }}` branch.
 
-            A new pull request has been created to test the changes. See ${{ steps.comment_new_pr.outputs.COMMENT_URL }} for more details.'
+            A new pull request has been created to test the changes. See ${{ env.COMMENT_URL }} for more details.'
           else
             body='Unable to cherry-pick the changes from `${{ github.head_ref }}` to the `${{ env.TEST_BRANCH }}` branch.
 
-            A new pull request has been created to manually resolve the merge conflicts and test the changes. See ${{ steps.comment_new_pr.outputs.COMMENT_URL }} for more details.'
+            A new pull request has been created to manually resolve the merge conflicts and test the changes. See ${{ env.COMMENT_URL }} for more details.'
           fi
           gh pr comment ${{ github.event.pull_request.number }} --body "${{ env.BOT_COMMENT_TAG }}
           $body"
 
       - name: Remove label from original pull request
-        if: ${{ steps.check_label.outcome == 'success' }}
+        if: ${{ env.SKIP == 'false' }}
         run: |
           gh pr edit ${{ github.event.pull_request.number }} --remove-label "${{ env.TRIGGER_LABEL }}"
