Refactor code to trigger on comments instead of label

diff --git a/.github/workflows/UpdateTestBranch.yaml b/.github/workflows/UpdateTestBranch.yaml
--- a/.github/workflows/UpdateTestBranch.yaml
+++ b/.github/workflows/UpdateTestBranch.yaml
@@ -1,25 +1,19 @@
 name: Update Test Branch
 
 on:
-  pull_request:
+  issue_comment:
     types:
-      labeled
-    branches:
-      - master
-      - main
+      created
 
 env:
   TEST_BRANCH: test/main
-  CPICK_BRANCH_TEMPLATE: cherry-pick/${{ github.head_ref }}
   FEATURE_TEST_PREFIX: test/
-  TRIGGER_LABEL: Ready for Test
   NOTICE_COMMENT_TAG: <!-- UpdateTestBranch/NOTICE -->
   COMMIT_COMMENT_TAG: <!-- UpdateTestBranch/COMMIT -->
   BOT_LABEL: Automated
   DISABLE_COMMENTS: false
-  FEATURE_TEST_BRANCH: test/${{ github.head_ref }}
+  FEATURE_TEST_BRANCH: 'test/feature-branch'
   SKIP_ALL: false
-  LABEL_MATCH: false
   FEATURE_COMMITS: ''
   PICKED_COMMITS: ''
   ADDED_COMMITS: ''
@@ -31,70 +25,65 @@ jobs:
   update_test_branch:
     name: Update Test Branch
     runs-on: ubuntu-latest
-    outputs:
-      LABEL_MATCH: ${{ env.LABEL_MATCH }}
+    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '!update-test')
     steps:
-      - name: Set environment variables
-        run: |
-          echo "TEST_BRANCH=${{ vars.UPDATETESTBRANCH_TEST_BRANCH || env.TEST_BRANCH }}" >> $GITHUB_ENV
-          echo "CPICK_BRANCH_TEMPLATE=${{ vars.UPDATETESTBRANCH_CPICK_BRANCH_TEMPLATE || env.CPICK_BRANCH_TEMPLATE }}" >> $GITHUB_ENV
-          echo "FEATURE_TEST_PREFIX=${{ vars.UPDATETESTBRANCH_FEATURE_TEST_PREFIX || env.FEATURE_TEST_PREFIX }}"
-          echo "FEATURE_TEST_BRANCH=${{ env.FEATURE_TEST_PREFIX }}${{ github.head_ref }}" >> $GITHUB_ENV
-          echo "TRIGGER_LABEL=${{ vars.UPDATETESTBRANCH_TRIGGER_LABEL || env.TRIGGER_LABEL }}" >> $GITHUB_ENV
-          echo "NOTICE_COMMENT_TAG=${{ vars.UPDATETESTBRANCH_NOTICE_COMMENT_TAG || env.NOTICE_COMMENT_TAG }}" >> $GITHUB_ENV
-          echo "COMMIT_COMMENT_TAG=${{ vars.UPDATETESTBRANCH_COMMIT_COMMENT_TAG || env.COMMIT_COMMENT_TAG }}" >> $GITHUB_ENV
-          echo "BOT_LABEL=${{ vars.UPDATETESTBRANCH_BOT_LABEL || env.BOT_LABEL }}" >> $GITHUB_ENV
-          echo "DISABLE_COMMENTS=${{ vars.UPDATETESTBRANCH_DISABLE_COMMENTS || env.DISABLE_COMMENTS }}" >> $GITHUB_ENV
-
-      - name: Check if label matches trigger label
-        run: |
-          triggerLabel="${{ env.TRIGGER_LABEL }}"
-          eventLabel="${{ github.event.label.name }}"
-
-          if [ "$eventLabel" != "$triggerLabel" ]; then
-            echo "SKIP_ALL=true" >> $GITHUB_ENV
-            echo "::notice::Label $eventLabel does not match trigger label $triggerLabel. Skipping update."
-          else
-            echo "LABEL_MATCH=true" >> $GITHUB_ENV
-          fi
-
-      - name: Checkout repository
-        if: ${{ env.SKIP_ALL == 'false' }}
-        uses: actions/checkout@v4
-
       - name: Set up Git
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
           git config --global user.name github-actions[bot]
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
-      - name: Check PR status
+      - name: Get PR object
+        id: pull_request
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
-          if [ "${{ github.head_ref }}" == "${{ env.TEST_BRANCH }}" ]; then
-            echo "::error::You cannot update the test branch `${{ env.TEST_BRANCH }}` with itself. Please use a different branch."
+          pr=$(gh pr view ${{ github.event.issue.number }} --json headRefName,baseRefName,state --jq '.headRefName, .baseRefName')
+          echo "HEAD_REF=$(echo $pr | jq -r '.[1]')" >> $GITHUB_OUTPUT
+          echo "BASE_REF=$(echo $pr | jq -r '.[2]')" >> $GITHUB_OUTPUT
+
+      - name: Set environment variables
+        if: ${{ env.SKIP_ALL == 'false' }}
+        run: |
+          echo "TEST_BRANCH=${{ vars.UPDATETESTBRANCH_TEST_BRANCH || env.TEST_BRANCH }}" >> $GITHUB_ENV
+          echo "FEATURE_TEST_PREFIX=${{ vars.UPDATETESTBRANCH_FEATURE_TEST_PREFIX || env.FEATURE_TEST_PREFIX }}"
+          echo "FEATURE_TEST_BRANCH=${{ env.FEATURE_TEST_PREFIX }}${{ steps.pull_request.outputs.HEAD_REF }}" >> $GITHUB_ENV
+          echo "TRIGGER_LABEL=${{ vars.UPDATETESTBRANCH_TRIGGER_LABEL || env.TRIGGER_LABEL }}" >> $GITHUB_ENV
+          echo "NOTICE_COMMENT_TAG=${{ vars.UPDATETESTBRANCH_NOTICE_COMMENT_TAG || env.NOTICE_COMMENT_TAG }}" >> $GITHUB_ENV
+          echo "COMMIT_COMMENT_TAG=${{ vars.UPDATETESTBRANCH_COMMIT_COMMENT_TAG || env.COMMIT_COMMENT_TAG }}" >> $GITHUB_ENV
+          echo "BOT_LABEL=${{ vars.UPDATETESTBRANCH_BOT_LABEL || env.BOT_LABEL }}" >> $GITHUB_ENV
+          echo "DISABLE_COMMENTS=${{ vars.UPDATETESTBRANCH_DISABLE_COMMENTS || env.DISABLE_COMMENTS }}" >> $GITHUB_ENV
+
+      - name: Check PR settings
+        if: ${{ env.SKIP_ALL == 'false' }}
+        run: |
+          if [ "${{ steps.pull_request.outputs.HEAD_REF }}" == "${{ env.TEST_BRANCH }}" ]; then
+            echo "::error::You cannot update the test branch `${{ env.TEST_BRANCH }}` with itself."
+            exit 1
+          fi
+          if [ "${{ steps.pull_request.outputs.BASE_REF }}" == ${{ env.TEST_BRANCH }} ]; then
+            echo "::error::The pull request ${{ github.event.issue.pull_request.html_url }} is already targeting the test branch `${{ env.TEST_BRANCH }}`."
             exit 1
           fi
 
+      - name: Checkout repository
+        if: ${{ env.SKIP_ALL == 'false' }}
+        uses: actions/checkout@v4
+
       - name: Check if ${{ env.TEST_BRANCH }} exists
         if: ${{ env.SKIP_ALL == 'false' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const { execSync } = require('child_process');
-            try {
-              execSync(`git fetch origin ${process.env.TEST_BRANCH}`);
-            } catch (error) {
-              core.setFailed(`Branch ${process.env.TEST_BRANCH} does not exist. Please create the branch and try again.`);
-            }
+        run: |
+          if [ -z "$(git ls-remote --heads origin ${{ env.TEST_BRANCH }})" ]; then
+            echo "::error::Branch ${{ env.TEST_BRANCH }} does not exist. Please create the branch or define a custom name by editing the repository variable 'UPDATETESTBRANCH_TEST_BRANCH' and try again."
+            exit 1
+          fi
 
       - name: Get list of feature commits
         id: get_feature_commits
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
-          git fetch origin ${{ github.base_ref }}
-          git fetch origin ${{ github.head_ref }}
-          feature_commits=$(git log --reverse --no-merges --pretty=format:%h origin/${{ github.base_ref }}..origin/${{ github.head_ref }})
+          git fetch origin ${{ steps.pull_request.outputs.BASE_REF }}
+          git fetch origin ${{ steps.pull_request.outputs.HEAD_REF }}
+          feature_commits=$(git log --reverse --no-merges --pretty=format:%h origin/${{ steps.pull_request.outputs.BASE_REF }}..origin/${{ steps.pull_request.outputs.HEAD_REF }})
 
           if [ -z "$feature_commits" ]; then
             echo "SKIP_ALL=true" >> $GITHUB_ENV
@@ -102,7 +91,7 @@ jobs:
             exit 0
           fi
 
-          feature_commits_pretty=$(git log --reverse --no-merges --pretty=format:"- %s (%H)" origin/${{ github.base_ref }}..origin/${{ github.head_ref }})
+          feature_commits_pretty=$(git log --reverse --no-merges --pretty=format:"- %s (%H)" origin/${{ steps.pull_request.outputs.BASE_REF }}..origin/${{ steps.pull_request.outputs.HEAD_REF }})
 
           echo -e 'Feature commits:\n'"$feature_commits_pretty"
           for commit in $feature_commits; do
@@ -116,7 +105,7 @@ jobs:
           } >> $GITHUB_ENV
 
       - name: Check if ${{ env.FEATURE_TEST_BRANCH }} exists
-        id: check_feature_test_branch
+        id: check_feat_test
         if: ${{ env.SKIP_ALL == 'false' }}
         run: |
           if [ -z "$(git ls-remote --heads origin ${{ env.FEATURE_TEST_BRANCH }})" ]; then
@@ -129,7 +118,7 @@ jobs:
 
       - name: Get list of already cherry-picked commits
         id: get_cherry_picked_commits
-        if: ${{ env.SKIP_ALL == 'false' && steps.check_feature_test_branch.outputs.SKIP_CHERRY_LIST == 'false' }}
+        if: ${{ env.SKIP_ALL == 'false' && steps.check_feat_test.outputs.SKIP_CHERRY_LIST == 'false' }}
         run: |
           git fetch origin ${{ env.TEST_BRANCH }}
           git fetch origin ${{ env.FEATURE_TEST_BRANCH }}
@@ -269,7 +258,7 @@ jobs:
             CP:'$commit
             git cherry-pick $commit 1>/dev/null || true
             if [ -n "$(git status --porcelain | grep '^U')" ]; then
-              echo '::error::Cherry-pick failed. Please see ${{ github.event.pull_request.html_url }} for more details.'
+              echo '::error::Cherry-pick failed. Please see ${{ github.event.issue.pull_request.html_url }} for more details.'
               exit 1
             fi
             git commit --amend -m "$message"
@@ -324,7 +313,7 @@ jobs:
           git reset --hard
           if [ -z "$(git log origin/${{ env.FEATURE_TEST_BRANCH }}..${{ env.FEATURE_TEST_BRANCH }})" ]; then
             echo "Pushing empty commit to ${{ env.FEATURE_TEST_BRANCH }} to create PR."
-            git commit --allow-empty -m 'Cherry-pick of `${{ github.head_ref }}` failed.
+            git commit --allow-empty -m 'Cherry-pick of `${{ steps.pull_request.outputs.HEAD_REF }}` failed.
             Manual resolution required.'
           fi
           git push origin ${{ env.FEATURE_TEST_BRANCH }}
@@ -344,15 +333,15 @@ jobs:
             TEST_PR_URL=$(gh pr create \
               --base ${{ env.TEST_BRANCH }} \
               --head ${{ env.FEATURE_TEST_BRANCH }} \
-              --title "${{ github.event.pull_request.title }} - Test" \
+              --title "${{ github.event.issue.title }} - Test" \
               --label ${{ env.BOT_LABEL }} \
               --assignee ${{ github.actor }} \
-              --body 'This automated pull request adds the cherry-picked changes from `${{ github.head_ref }}` to `${{ env.TEST_BRANCH }}`.
-              See #${{ github.event.pull_request.number }} for more details.')
+              --body 'This automated pull request adds the cherry-picked changes from `${{ steps.pull_request.outputs.HEAD_REF }}` to `${{ env.TEST_BRANCH }}`.
+              See ${{ github.event.issue.pull_request.html_url }} for more details.')
             echo "::notice::$TEST_PR_URL created."
           else
             TEST_PR_URL=$(gh pr edit ${{ env.FEATURE_TEST_BRANCH }} \
-              --add-assignee ${{ github.actor }})
+              --add-assignee ${{ github.event.issue.assignees.login }})
             echo "::notice::$TEST_PR_URL updated."
           fi
           echo "TEST_PR_URL=$TEST_PR_URL" >> $GITHUB_ENV
@@ -414,7 +403,7 @@ jobs:
           git cherry-pick '"$failed_commit"'
           ```
           2) Resolve the merge conflicts and push the changes.
-          3) Re-run the workflow by adding the label `${{ env.TRIGGER_LABEL }}` to ${{ github.event.pull_request.html_url }} again.'
+          3) Re-run the workflow by commenting `!update-test-branch` in ${{ github.event.issue.pull_request.html_url }} again.'
 
           COMMENT_URL=$(gh pr comment ${{ env.TEST_PR_URL }} --body "${{ env.NOTICE_COMMENT_TAG }}
           $body")
@@ -425,33 +414,13 @@ jobs:
         if: ${{ env.SKIP_ALL == 'false' && env.DISABLE_COMMENTS == 'false' }}
         run: |
           if [ "${{ steps.cherry_pick.outcome }}" == "success" ]; then
-            body='The cherry-picked changes from `${{ github.head_ref }}` are ready to be added to the `${{ env.TEST_BRANCH }}` branch.
+            body='The cherry-picked changes from `${{ steps.pull_request.outputs.HEAD_REF }}` are ready to be added to the `${{ env.TEST_BRANCH }}` branch.
 
             A new pull request has been created to test the changes. See ${{ steps.comment_on_new_pr.outputs.COMMENT_URL }} for more details.'
           else
-            body='Unable to cherry-pick the changes from `${{ github.head_ref }}` to the `${{ env.TEST_BRANCH }}` branch.
+            body='Unable to cherry-pick the changes from `${{ steps.pull_request.outputs.HEAD_REF }}` to the `${{ env.TEST_BRANCH }}` branch.
 
             A new pull request has been created to manually resolve the merge conflicts and test the changes. See ${{ steps.comment_on_new_pr.outputs.COMMENT_URL }} for more details.'
           fi
-          gh pr comment ${{ github.event.pull_request.number }} --body '${{ env.NOTICE_COMMENT_TAG }}
+          gh pr comment ${{ github.event.issue.number }} --body '${{ env.NOTICE_COMMENT_TAG }}
           $body'
-
-  remove_label:
-    name: Remove trigger label
-    runs-on: ubuntu-latest
-    needs: update_test_branch
-    if: ${{ always() && needs.update_test_branch.outputs.LABEL_MATCH == 'true' }}
-    steps:
-      - name: Checkout repository
-        if: ${{ env.SKIP_ALL == 'false' }}
-        uses: actions/checkout@v4.1.1
-
-      - name: Set up Git
-        if: ${{ env.SKIP_ALL == 'false' }}
-        run: |
-          git config --global user.name github-actions[bot]
-          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-
-      - name: Remove "${{ env.TRIGGER_LABEL }}" label
-        run: |
-          gh pr edit ${{ github.event.pull_request.number }} --remove-label "${{ env.TRIGGER_LABEL }}"
