Use core.setFailed from github-script to throw errors

diff --git a/.github/workflows/UpdateTestBranch.yaml b/.github/workflows/UpdateTestBranch.yaml
--- a/.github/workflows/UpdateTestBranch.yaml
+++ b/.github/workflows/UpdateTestBranch.yaml
@@ -22,19 +22,21 @@ jobs:
       - name: Check PR status
         id: check_pr
         continue-on-error: true
-        run: |
-          if [ ${{github.head_ref}} == ${{env.TEST_BRANCH}} ]; then
-            echo "::error::You cannot update the ${{env.TEST_BRANCH}} branch with itself. Please create a new branch and try again."
-          fi
-          if [ ${{github.head_ref}} == "dev/"* ]; then
-            echo "::error::The head branch of this pull request begins with "dev/". Changes from this branch will not be cherry-picked into the ${{env.TEST_BRANCH}} branch."
-          fi
-          if [ "${{ github.event.pull_request.draft }}" = "true" ]; then
-            echo "::error::This pull request is a draft. Update workflow cancelled."
-          fi
-          if [[ "${{ github.event.pull_request.labels }}" == *"Automated"* ]]; then
-            echo "::error::This pull request is automated. Update workflow cancelled."
-          fi
+        uses: actions/github-script@v7
+        with:
+          script: |
+            if (github.context.payload.pull_request.draft) {
+              core.setFailed('This pull request is a draft. Update workflow cancelled.');
+            }
+            if (github.context.payload.pull_request.labels.some(label => label.name === 'Automated')) {
+              core.setFailed('This pull request is automated. Update workflow cancelled.');
+            }
+            if (github.context.payload.pull_request.head.ref === process.env.TEST_BRANCH) {
+              core.setFailed(`You cannot update the ${process.env.TEST_BRANCH} branch with itself. Please create a new branch and try again.`);
+            }
+            if (github.context.payload.pull_request.head.ref.startsWith('dev/')) {
+              core.setFailed(`The head branch of this pull request begins with "dev/". Changes from this branch will not be cherry-picked into the ${process.env.TEST_BRANCH} branch.`);
+            }
 
       - name: Checkout repository
         if: ${{ steps.check_pr.outcome == 'success' }}
@@ -49,11 +51,15 @@ jobs:
       - name: Check if ${{ env.TEST_BRANCH }} exists
         id: check_test_branch
         if: ${{ steps.check_pr.outcome == 'success' }}
-        run: |
-          if [ -z "$(git ls-remote --heads origin ${{ env.TEST_BRANCH }})" ]; then
-            echo "::error::Branch ${{ env.TEST_BRANCH }} does not exist. Please create the branch and try again."
-          fi
-          git fetch origin ${{ env.TEST_BRANCH }}
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const { execSync } = require('child_process');
+            try {
+              execSync(`git fetch origin ${process.env.TEST_BRANCH}`);
+            } catch (error) {
+              core.setFailed(`Branch ${process.env.TEST_BRANCH} does not exist. Please create the branch and try again.`);
+            }
 
       - name: Get newest commit hash
         id: get_commit_hash
@@ -75,6 +81,7 @@ jobs:
 
       - name: Squash merge ${{ github.head_ref }} into temporary cherry-pick branch
         id: merge_commit
+        continue-on-error: true
         if: ${{ steps.check_pr.outcome == 'success' }}
         run: |
           git fetch origin ${{ github.head_ref }}
@@ -82,7 +89,8 @@ jobs:
 
           git merge --squash -n "origin/${{ github.head_ref }}"
           if [ -z "$(git status --porcelain | grep '^U')" ]; then
-            echo "::error::Unable to create squash merge commit. Please merge the latest changes to ${{ github.base_ref}} into the head branch ${{ github.head_ref }} and try again."
+            echo "::error::Unmerged files detected."
+            exit 1
           fi
           git commit -m "$merge_commit_msg"
           git push origin "${{ steps.create_temp_branch.outputs.CHERRY_PICK_BRANCH }}"
@@ -90,9 +98,17 @@ jobs:
           echo "MERGE_COMMIT_MSG=$merge_commit_msg" >> "$GITHUB_OUTPUT"
           echo "MERGE_COMMIT_SHA=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
 
+      - name: Report Error
+        if: ${{ steps.merge_commit.outputs.MERGE_COMMIT_SHA == '' }}
+        uses: actions/github-script@v7
+        with:
+          script:
+            core.setFailed('Unable to create squash merge commit. Please merge the latest changes to ${{ github.base_ref}} into the head branch ${{ github.head_ref }} and try again.')
+
       - name: Create/Checkout ${{ env.FEATURE_TEST_BRANCH }}
         if: ${{ steps.check_pr.outcome == 'success' }}
         run: |
+          git fetch origin ${{ env.TEST_BRANCH }}
           if [ -z "$(git ls-remote --heads origin ${{ env.FEATURE_TEST_BRANCH }})" ]; then
             git checkout ${{ env.TEST_BRANCH }}
             git checkout -b ${{ env.FEATURE_TEST_BRANCH }}
@@ -110,6 +126,7 @@ jobs:
           git cherry-pick --no-commit ${{ steps.merge_commit.outputs.MERGE_COMMIT_SHA }} || true
           if [ -z "$(git status --porcelain | grep '^U')" ]; then
             echo "::error::Cherry-pick failed. Please cherry-pick the commit '${{ steps.merge_commit.outputs.MERGE_COMMIT_MSG }} (${{ steps.merge_commit.outputs.MERGE_COMMIT_SHA }}) into ${{ env.FEATURE_TEST_BRANCH}}"
+            exit 1
           fi
 
       - name: "On success: Commit & push cherry-picked changes"
